name = "anonymous-chat"
type = "javascript"
main = "src/main.ts"
compatibility_date = "2024-12-18"

[env.production]
name = "anonymous-chat-prod"

[build]
command = "npm run build"
cwd = "./"
outdir = "./dist"

[[routes]]
pattern = "*"
zone_name = "example.com"
